name: CloneCover
main: pgDev.bukkit.CloneCover.CloneCover
version: 0.1
author: PG Dev Team
authors: [Devil Boy]
description: Hide in the crowd!
depend: [DisguiseCraft]

permissions:
    clonecover.exempt:
        default: false
        description: Is not disguised upon joining.